"""
Django settings for django_fishface project.

For more information on this file, see
https://docs.djangoproject.com/en/1.6/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.6/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import logging
import logging.handlers
from django.utils.crypto import get_random_string

BASE_DIR = os.path.dirname(os.path.dirname(__file__))

HOME = os.environ['HOME']
ALT_ROOT = HOME

# TODO: change for full production
DB_PASSWD_FILE = os.path.join(BASE_DIR, 'fishface_db_password')
REDIS_PASSWORD_FILE = os.path.join(ALT_ROOT, 'etc', 'redis', 'redis_password')
REDIS_HOSTNAME_FILE = os.path.join(ALT_ROOT, 'var', 'run', 'redis.hostname')

# These get imported/generated later.
DB_PASSWD = None
SECRET_KEY = None


def generate_and_collect_secret_keys():
    length = 50
    chars = 'abcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*(-_=+)'
    django_key = get_random_string(length, chars)

    try:
        with open(DB_PASSWD_FILE, 'rt') as f:
            db_key = f.read().strip()
    except IOError:
        logging.warning('No database key file found during generation of secret_keys.py!')
        db_key = ''

    with open(os.path.join(
            os.path.abspath(os.path.dirname(__file__)),
            'secret_keys.py'), 'wt') as f:
        f.write("""# This file is autogenerated if it doesn't exist but is now safe to edit.
SECRET_KEY = '{}'
DB_PASSWD = '{}'
""".format(django_key, db_key))

try:
    from secret_keys import *
except ImportError:
    generate_and_collect_secret_keys()
    from secret_keys import *

try:
    from dev_settings import (
        DEBUG,
        TEMPLATE_DEBUG,
        DATABASES,
        IMAGERY_SERVER_HOST,
        IMAGERY_SERVER_PORT,
    )
except ImportError:
    DEBUG = False
    TEMPLATE_DEBUG = False

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': 'fishfacedb',
            'USER': 'fishfacedbuser',
            'PASSWORD': DB_PASSWD,
            'HOST': 'localhost',
            'PORT': '',
        },
    }

    IMAGERY_SERVER_HOST = 'raspi'
    IMAGERY_SERVER_PORT = 18765

# Set to wildcard pending fixed IP assignment
# TODO: After fixed IP assignment, put real value here.
ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'south',
    'djff',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
)

ROOT_URLCONF = 'django_fishface.urls'

WSGI_APPLICATION = 'django_fishface.wsgi.application'


# Internationalization
# https://docs.djangoproject.com/en/1.6/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'America/Los_Angeles'

USE_I18N = True
USE_L10N = False
USE_TZ = True

DATETIME_FORMAT = 'Y-m-d H:i:s.u'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.6/howto/static-files/

STATIC_ROOT = os.path.join('djff/static/')
STATIC_URL = '/static/'

MEDIA_ROOT = '/mnt/server_storage/media/'
MEDIA_URL = '/media/'

# DJFF settings

TELEMETRY_URL = "http://{}:{}/telemetry/".format(IMAGERY_SERVER_HOST, IMAGERY_SERVER_PORT)

# Logging
PRIMARY_LOGGER = logging.getLogger('djff')
PRIMARY_LOGGER.setLevel(logging.DEBUG)

formatter = logging.Formatter('%(asctime)s %(levelname)s %(message)s')

LOG_TO_CONSOLE = True
LOG_TO_FILE = True
LOG_TO_SYSLOG = True

SYSLOG_LOG_LEVEL = logging.INFO
CONSOLE_LOG_LEVEL = logging.DEBUG
FILE_LOG_LEVEL = logging.DEBUG

if LOG_TO_SYSLOG:
    syslog_handler = logging.handlers.SysLogHandler()
    syslog_handler.setLevel(SYSLOG_LOG_LEVEL)
    syslog_handler.setFormatter(formatter)

    PRIMARY_LOGGER.addHandler(syslog_handler)

if LOG_TO_CONSOLE:
    console_handler = logging.StreamHandler()
    console_handler.setLevel(CONSOLE_LOG_LEVEL)
    console_handler.setFormatter(formatter)

    PRIMARY_LOGGER.addHandler(console_handler)

if LOG_TO_FILE:
    file_handler = logging.FileHandler('django_fishface.log')
    file_handler.setLevel(FILE_LOG_LEVEL)
    file_handler.setFormatter(formatter)

    PRIMARY_LOGGER.addHandler(file_handler)

# Celery configuration
try:
    if os.path.isfile(REDIS_PASSWORD_FILE):
        with open(REDIS_PASSWORD_FILE, 'rt') as f:
            redis_password = f.read().strip()
except IOError:
    logging.warning('No redis key file found.  Disabling redis authentication.')
    redis_password = ''

try:
    with open(REDIS_HOSTNAME_FILE, 'rt') as redis_hostname_file:
        redis_hostname = redis_hostname_file.read().strip()
except IOError:
    logging.warning('No redis hostname file found.  Using localhost.')
    redis_hostname = 'localhost'


if redis_password != '':
    broker_url = 'redis://:{password}@{hostname}'.format(
        password=redis_password, hostname=redis_hostname)
    result_url = broker_url
else:
    broker_url = 'redis://{hostname}'.format(password=redis_password)
    result_url = broker_url

BROKER_URL = broker_url
CELERY_RESULT_BACKEND = result_url

CELERY_ACCEPT_CONTENT = ['pickle', 'json']
CELERY_TASK_SERIALIZER = 'pickle'
CELERY_RESULT_SERIALIZER = 'pickle'