# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: merrellyze.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='merrellyze.proto',
  package='merrellyze',
  syntax='proto3',
  serialized_pb=_b('\n\x10merrellyze.proto\x12\nmerrellyze\"A\n\x05Image\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04path\x18\x02 \x01(\t\x12\x1e\n\x03\x63\x61l\x18\x03 \x01(\x0b\x32\x11.merrellyze.Image\"g\n\x10\x43\x61ptureJobRecord\x12\n\n\x02id\x18\x01 \x01(\x05\x12$\n\tcal_image\x18\x02 \x01(\x0b\x32\x11.merrellyze.Image\x12!\n\x06images\x18\x03 \x03(\x0b\x32\x11.merrellyze.Image\"A\n\x14\x45llipseSearchRequest\x12)\n\x03\x63jr\x18\x01 \x03(\x0b\x32\x1c.merrellyze.CaptureJobRecord\"4\n\x15\x45rrorCJREllipseSearch\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x8c\x01\n\x15\x45llipseSearchResponse\x12\x36\n\x10\x63jrs_in_progress\x18\x01 \x03(\x0b\x32\x1c.merrellyze.CaptureJobRecord\x12;\n\x10\x63jrs_with_errors\x18\x02 \x03(\x0b\x32!.merrellyze.ErrorCJREllipseSearch\":\n\rResultRequest\x12)\n\x03\x63jr\x18\x01 \x03(\x0b\x32\x1c.merrellyze.CaptureJobRecord\" \n\x08Location\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\"\x9f\x01\n\nEllipseTag\x12\x10\n\x08image_id\x18\x01 \x01(\x05\x12#\n\x05start\x18\x02 \x01(\x0b\x32\x14.merrellyze.Location\x12!\n\x03\x65nd\x18\x03 \x01(\x0b\x32\x14.merrellyze.Location\x12\r\n\x05score\x18\x04 \x01(\x02\x12\x16\n\x0etagging_method\x18\x05 \x01(\t\x12\x10\n\x08revision\x18\x06 \x01(\x05\"@\n\rEllipseTagCJR\x12\n\n\x02id\x18\x01 \x03(\x05\x12#\n\x03tag\x18\x02 \x03(\x0b\x32\x16.merrellyze.EllipseTag\"p\n\x0eResultResponse\x12(\n\x05ready\x18\x01 \x03(\x0b\x32\x19.merrellyze.EllipseTagCJR\x12\x34\n\tnot_ready\x18\x02 \x01(\x0b\x32!.merrellyze.EllipseSearchResponse2i\n\x0f\x45llipseSearcher\x12V\n\rEllipseSearch\x12 .merrellyze.EllipseSearchRequest\x1a!.merrellyze.EllipseSearchResponse\"\x00\x32W\n\rResultFetcher\x12\x46\n\x0bResultFetch\x12\x19.merrellyze.ResultRequest\x1a\x1a.merrellyze.ResultResponse\"\x00\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_IMAGE = _descriptor.Descriptor(
  name='Image',
  full_name='merrellyze.Image',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='merrellyze.Image.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='path', full_name='merrellyze.Image.path', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cal', full_name='merrellyze.Image.cal', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=97,
)


_CAPTUREJOBRECORD = _descriptor.Descriptor(
  name='CaptureJobRecord',
  full_name='merrellyze.CaptureJobRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='merrellyze.CaptureJobRecord.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cal_image', full_name='merrellyze.CaptureJobRecord.cal_image', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='images', full_name='merrellyze.CaptureJobRecord.images', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=202,
)


_ELLIPSESEARCHREQUEST = _descriptor.Descriptor(
  name='EllipseSearchRequest',
  full_name='merrellyze.EllipseSearchRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cjr', full_name='merrellyze.EllipseSearchRequest.cjr', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=204,
  serialized_end=269,
)


_ERRORCJRELLIPSESEARCH = _descriptor.Descriptor(
  name='ErrorCJREllipseSearch',
  full_name='merrellyze.ErrorCJREllipseSearch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='merrellyze.ErrorCJREllipseSearch.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='message', full_name='merrellyze.ErrorCJREllipseSearch.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=271,
  serialized_end=323,
)


_ELLIPSESEARCHRESPONSE = _descriptor.Descriptor(
  name='EllipseSearchResponse',
  full_name='merrellyze.EllipseSearchResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cjrs_in_progress', full_name='merrellyze.EllipseSearchResponse.cjrs_in_progress', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cjrs_with_errors', full_name='merrellyze.EllipseSearchResponse.cjrs_with_errors', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=326,
  serialized_end=466,
)


_RESULTREQUEST = _descriptor.Descriptor(
  name='ResultRequest',
  full_name='merrellyze.ResultRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cjr', full_name='merrellyze.ResultRequest.cjr', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=468,
  serialized_end=526,
)


_LOCATION = _descriptor.Descriptor(
  name='Location',
  full_name='merrellyze.Location',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='merrellyze.Location.x', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='merrellyze.Location.y', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=528,
  serialized_end=560,
)


_ELLIPSETAG = _descriptor.Descriptor(
  name='EllipseTag',
  full_name='merrellyze.EllipseTag',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image_id', full_name='merrellyze.EllipseTag.image_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='start', full_name='merrellyze.EllipseTag.start', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='end', full_name='merrellyze.EllipseTag.end', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='score', full_name='merrellyze.EllipseTag.score', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tagging_method', full_name='merrellyze.EllipseTag.tagging_method', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='revision', full_name='merrellyze.EllipseTag.revision', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=563,
  serialized_end=722,
)


_ELLIPSETAGCJR = _descriptor.Descriptor(
  name='EllipseTagCJR',
  full_name='merrellyze.EllipseTagCJR',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='merrellyze.EllipseTagCJR.id', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tag', full_name='merrellyze.EllipseTagCJR.tag', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=724,
  serialized_end=788,
)


_RESULTRESPONSE = _descriptor.Descriptor(
  name='ResultResponse',
  full_name='merrellyze.ResultResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ready', full_name='merrellyze.ResultResponse.ready', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='not_ready', full_name='merrellyze.ResultResponse.not_ready', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=790,
  serialized_end=902,
)

_IMAGE.fields_by_name['cal'].message_type = _IMAGE
_CAPTUREJOBRECORD.fields_by_name['cal_image'].message_type = _IMAGE
_CAPTUREJOBRECORD.fields_by_name['images'].message_type = _IMAGE
_ELLIPSESEARCHREQUEST.fields_by_name['cjr'].message_type = _CAPTUREJOBRECORD
_ELLIPSESEARCHRESPONSE.fields_by_name['cjrs_in_progress'].message_type = _CAPTUREJOBRECORD
_ELLIPSESEARCHRESPONSE.fields_by_name['cjrs_with_errors'].message_type = _ERRORCJRELLIPSESEARCH
_RESULTREQUEST.fields_by_name['cjr'].message_type = _CAPTUREJOBRECORD
_ELLIPSETAG.fields_by_name['start'].message_type = _LOCATION
_ELLIPSETAG.fields_by_name['end'].message_type = _LOCATION
_ELLIPSETAGCJR.fields_by_name['tag'].message_type = _ELLIPSETAG
_RESULTRESPONSE.fields_by_name['ready'].message_type = _ELLIPSETAGCJR
_RESULTRESPONSE.fields_by_name['not_ready'].message_type = _ELLIPSESEARCHRESPONSE
DESCRIPTOR.message_types_by_name['Image'] = _IMAGE
DESCRIPTOR.message_types_by_name['CaptureJobRecord'] = _CAPTUREJOBRECORD
DESCRIPTOR.message_types_by_name['EllipseSearchRequest'] = _ELLIPSESEARCHREQUEST
DESCRIPTOR.message_types_by_name['ErrorCJREllipseSearch'] = _ERRORCJRELLIPSESEARCH
DESCRIPTOR.message_types_by_name['EllipseSearchResponse'] = _ELLIPSESEARCHRESPONSE
DESCRIPTOR.message_types_by_name['ResultRequest'] = _RESULTREQUEST
DESCRIPTOR.message_types_by_name['Location'] = _LOCATION
DESCRIPTOR.message_types_by_name['EllipseTag'] = _ELLIPSETAG
DESCRIPTOR.message_types_by_name['EllipseTagCJR'] = _ELLIPSETAGCJR
DESCRIPTOR.message_types_by_name['ResultResponse'] = _RESULTRESPONSE

Image = _reflection.GeneratedProtocolMessageType('Image', (_message.Message,), dict(
  DESCRIPTOR = _IMAGE,
  __module__ = 'merrellyze_pb2'
  # @@protoc_insertion_point(class_scope:merrellyze.Image)
  ))
_sym_db.RegisterMessage(Image)

CaptureJobRecord = _reflection.GeneratedProtocolMessageType('CaptureJobRecord', (_message.Message,), dict(
  DESCRIPTOR = _CAPTUREJOBRECORD,
  __module__ = 'merrellyze_pb2'
  # @@protoc_insertion_point(class_scope:merrellyze.CaptureJobRecord)
  ))
_sym_db.RegisterMessage(CaptureJobRecord)

EllipseSearchRequest = _reflection.GeneratedProtocolMessageType('EllipseSearchRequest', (_message.Message,), dict(
  DESCRIPTOR = _ELLIPSESEARCHREQUEST,
  __module__ = 'merrellyze_pb2'
  # @@protoc_insertion_point(class_scope:merrellyze.EllipseSearchRequest)
  ))
_sym_db.RegisterMessage(EllipseSearchRequest)

ErrorCJREllipseSearch = _reflection.GeneratedProtocolMessageType('ErrorCJREllipseSearch', (_message.Message,), dict(
  DESCRIPTOR = _ERRORCJRELLIPSESEARCH,
  __module__ = 'merrellyze_pb2'
  # @@protoc_insertion_point(class_scope:merrellyze.ErrorCJREllipseSearch)
  ))
_sym_db.RegisterMessage(ErrorCJREllipseSearch)

EllipseSearchResponse = _reflection.GeneratedProtocolMessageType('EllipseSearchResponse', (_message.Message,), dict(
  DESCRIPTOR = _ELLIPSESEARCHRESPONSE,
  __module__ = 'merrellyze_pb2'
  # @@protoc_insertion_point(class_scope:merrellyze.EllipseSearchResponse)
  ))
_sym_db.RegisterMessage(EllipseSearchResponse)

ResultRequest = _reflection.GeneratedProtocolMessageType('ResultRequest', (_message.Message,), dict(
  DESCRIPTOR = _RESULTREQUEST,
  __module__ = 'merrellyze_pb2'
  # @@protoc_insertion_point(class_scope:merrellyze.ResultRequest)
  ))
_sym_db.RegisterMessage(ResultRequest)

Location = _reflection.GeneratedProtocolMessageType('Location', (_message.Message,), dict(
  DESCRIPTOR = _LOCATION,
  __module__ = 'merrellyze_pb2'
  # @@protoc_insertion_point(class_scope:merrellyze.Location)
  ))
_sym_db.RegisterMessage(Location)

EllipseTag = _reflection.GeneratedProtocolMessageType('EllipseTag', (_message.Message,), dict(
  DESCRIPTOR = _ELLIPSETAG,
  __module__ = 'merrellyze_pb2'
  # @@protoc_insertion_point(class_scope:merrellyze.EllipseTag)
  ))
_sym_db.RegisterMessage(EllipseTag)

EllipseTagCJR = _reflection.GeneratedProtocolMessageType('EllipseTagCJR', (_message.Message,), dict(
  DESCRIPTOR = _ELLIPSETAGCJR,
  __module__ = 'merrellyze_pb2'
  # @@protoc_insertion_point(class_scope:merrellyze.EllipseTagCJR)
  ))
_sym_db.RegisterMessage(EllipseTagCJR)

ResultResponse = _reflection.GeneratedProtocolMessageType('ResultResponse', (_message.Message,), dict(
  DESCRIPTOR = _RESULTRESPONSE,
  __module__ = 'merrellyze_pb2'
  # @@protoc_insertion_point(class_scope:merrellyze.ResultResponse)
  ))
_sym_db.RegisterMessage(ResultResponse)


import abc
import six
from grpc.beta import implementations as beta_implementations
from grpc.framework.common import cardinality
from grpc.framework.interfaces.face import utilities as face_utilities

class BetaEllipseSearcherServicer(six.with_metaclass(abc.ABCMeta, object)):
  """<fill me in later!>"""
  @abc.abstractmethod
  def EllipseSearch(self, request, context):
    raise NotImplementedError()

class BetaEllipseSearcherStub(six.with_metaclass(abc.ABCMeta, object)):
  """The interface to which stubs will conform."""
  @abc.abstractmethod
  def EllipseSearch(self, request, timeout):
    raise NotImplementedError()
  EllipseSearch.future = None

def beta_create_EllipseSearcher_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
  import merrellyze_pb2
  import merrellyze_pb2
  request_deserializers = {
    ('merrellyze.EllipseSearcher', 'EllipseSearch'): merrellyze_pb2.EllipseSearchRequest.FromString,
  }
  response_serializers = {
    ('merrellyze.EllipseSearcher', 'EllipseSearch'): merrellyze_pb2.EllipseSearchResponse.SerializeToString,
  }
  method_implementations = {
    ('merrellyze.EllipseSearcher', 'EllipseSearch'): face_utilities.unary_unary_inline(servicer.EllipseSearch),
  }
  server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
  return beta_implementations.server(method_implementations, options=server_options)

def beta_create_EllipseSearcher_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
  import merrellyze_pb2
  import merrellyze_pb2
  request_serializers = {
    ('merrellyze.EllipseSearcher', 'EllipseSearch'): merrellyze_pb2.EllipseSearchRequest.SerializeToString,
  }
  response_deserializers = {
    ('merrellyze.EllipseSearcher', 'EllipseSearch'): merrellyze_pb2.EllipseSearchResponse.FromString,
  }
  cardinalities = {
    'EllipseSearch': cardinality.Cardinality.UNARY_UNARY,
  }
  stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
  return beta_implementations.dynamic_stub(channel, 'merrellyze.EllipseSearcher', cardinalities, options=stub_options)

class BetaResultFetcherServicer(six.with_metaclass(abc.ABCMeta, object)):
  """<fill me in later!>"""
  @abc.abstractmethod
  def ResultFetch(self, request, context):
    raise NotImplementedError()

class BetaResultFetcherStub(six.with_metaclass(abc.ABCMeta, object)):
  """The interface to which stubs will conform."""
  @abc.abstractmethod
  def ResultFetch(self, request, timeout):
    raise NotImplementedError()
  ResultFetch.future = None

def beta_create_ResultFetcher_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
  import merrellyze_pb2
  import merrellyze_pb2
  request_deserializers = {
    ('merrellyze.ResultFetcher', 'ResultFetch'): merrellyze_pb2.ResultRequest.FromString,
  }
  response_serializers = {
    ('merrellyze.ResultFetcher', 'ResultFetch'): merrellyze_pb2.ResultResponse.SerializeToString,
  }
  method_implementations = {
    ('merrellyze.ResultFetcher', 'ResultFetch'): face_utilities.unary_unary_inline(servicer.ResultFetch),
  }
  server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
  return beta_implementations.server(method_implementations, options=server_options)

def beta_create_ResultFetcher_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
  import merrellyze_pb2
  import merrellyze_pb2
  request_serializers = {
    ('merrellyze.ResultFetcher', 'ResultFetch'): merrellyze_pb2.ResultRequest.SerializeToString,
  }
  response_deserializers = {
    ('merrellyze.ResultFetcher', 'ResultFetch'): merrellyze_pb2.ResultResponse.FromString,
  }
  cardinalities = {
    'ResultFetch': cardinality.Cardinality.UNARY_UNARY,
  }
  stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
  return beta_implementations.dynamic_stub(channel, 'merrellyze.ResultFetcher', cardinalities, options=stub_options)
# @@protoc_insertion_point(module_scope)
